language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

install:
  - curl https://nodejs.org/dist/v0.12.7/node-v0.12.7-sunos-x64.tar.gz > node.tar.gz
  - tar xf node.tar.gz
  - export PATH=$PATH:$pwd/node-v0.12.7-linux-x64/bin

script:
  - rustc --version
  - make
  - make test
  - make html

notifications:
  email:
    - mdinger.bugzilla@gmail.com

# uses a personal token from @steveklabnik
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

branches:
  only: master
